[buildPlans.Daydream]
family = "Daydream"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.Daydream.variants.design]
one = "base-long-top-serif"
three = "flat-top-serifless"
four = "closed-serifed"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifed-crossbar"
nine = "open-contour"
zero = "oval-long-dotted"
capital-b = "more-asymmetric-bilateral-serifed"
capital-g = "toothless-corner-serifed-capped"
capital-i = "short-serifed"
capital-j = "descending-serifed-symmetric"
capital-k = "symmetric-touching-serifed"
capital-m = "flat-bottom-serifed"
capital-p = "open-serifed"
capital-q = "crossing-curly-tailed"
a = "double-storey-hook-inward-serifed-tailed"
b = "toothless-corner-serifed"
d = "tailed-serifed"
f = "flat-hook-serifed"
g = "double-storey"
k = "symmetric-touching-serifed"
l = "zshaped"
q = "top-cut-straight-serifed"
r = "corner-hooked-serifed"
t = "flat-hook-short-neck2"
u = "tailed-serifed"
eszet = "longs-s-lig-bottom-serifed"
capital-thorn = "motion-serifed"
lower-thorn = "motion-serifed"
lower-delta = "flat-top"
lower-iota = "serifed-diagonal-tailed"
lower-kappa = "curly-top-left-and-bottom-right-serifed"
lower-lambda = "tailed-turn"
lower-mu = "tailed-motion-serifed"
lower-chi = "semi-chancery-straight-serifed"
partial-derivative = "closed-contour"
cyrl-a = "double-storey-hook-inward-serifed-tailed"
cyrl-capital-ze = "bilateral-serifed"
cyrl-ze = "bilateral-serifed"
cyrl-capital-ka = "curly-serifed"
cyrl-ka = "curly-serifed"
asterisk = "hex-high"
number-sign = "slanted"
at = "compact"
percent = "rings-continuous-slash"
micro-sign = "tailed-motion-serifed"
decorative-angle-brackets = "tall"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

[buildPlans.Daydream.variants.italic]
one = "base-long-top-serif"
three = "flat-top-serifless"
four = "closed-serifed"
five = "oblique-flat-serifless"
six = "open-contour"
seven = "straight-serifed-crossbar"
nine = "open-contour"
zero = "oval-long-dotted"
capital-b = "more-asymmetric-bilateral-serifed"
capital-g = "toothless-corner-serifed-capped"
capital-i = "short-serifed"
capital-j = "descending-serifed-symmetric"
capital-k = "symmetric-touching-serifed"
capital-m = "flat-bottom-serifed"
capital-p = "open-serifed"
capital-q = "crossing-curly-tailed"
a = "single-storey-earless-corner-tailed"
b = "toothless-rounded-serifed"
c = "unilateral-serifed"
f = "flat-hook-extended"
h = "tailed-motion-serifed"
i = "serifed-flat-tailed"
k = "symmetric-touching-tri-serifed"
l = "serifed-flat-tailed"
m = "tailed-top-left-serifed"
n = "tailed-motion-serifed"
p = "eared-motion-serifed"
q = "top-cut-straight-serifless"
r = "corner-hooked-top-serifed"
s = "bilateral-serifed"
x = "semi-chancery-straight-serifless"
long-s = "bent-hook-serifless"
eszet = "longs-s-lig-serifless"
lower-iota = "serifed-diagonal-tailed"
lower-lambda = "tailed-turn"
lower-chi = "semi-chancery-straight-serifed"
partial-derivative = "closed-contour"
cyrl-a = "single-storey-earless-corner-tailed"
cyrl-zhe = "cursive"
cyrl-capital-ze = "bilateral-serifed"
cyrl-ze = "bilateral-serifed"
cyrl-capital-ka = "curly-serifed"
cyrl-ka = "curly-tri-serifed"
cyrl-el = "tailed"
cyrl-em = "flat-bottom-motion-serifed"
cyrl-en = "tailed-top-left-serifed"
cyrl-ef = "top-serifed"
cyrl-che = "tailed"
cyrl-yery = "cursive-tailed"
cyrl-e = "unilateral-serifed"
at = "compact"

[buildPlans.Daydream.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.Daydream.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.Daydream.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.Daydream.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
